# Generated by Django 3.0.2 on 2020-04-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Nữ'), (1, 'Nam'), (2, 'Không xác định')], default=0, null=True),
        ),
    ]
