# Generated by Django 3.0.5 on 2020-04-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200413_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentblog',
            old_name='comment',
            new_name='comment_blog',
        ),
    ]
